apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  db-name: bWVzc2FnaW5nX2Ri # messaging_db (base64 encoded)
  db-user: ZGphbmdvX3VzZXI= # django_user (base64 encoded)
  db-password: c2VjdXJlX3Bhc3N3b3JkXzEyMw== # secure_password_123 (base64 encoded)
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmUtbWFrZS1pdC12ZXJ5LWxvbmctYW5kLXNlY3VyZQ== # your-secret-key-here-make-it-very-long-and-secure (base64 encoded)